version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: commute-connect
    networks:
      - bryanloh
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - bryanloh
networks:
  bryanloh:
